

export const data =[
    { id:'1', 
    propertyname:"Ace Divino",
    address1:"Greater Noida West",
    address2:"Plot No. GH 14A, Sector 1 Noida Extension, Greater Noida",
    PropertyID:"HZ29",
    RERANO:"UPRERAPRJ6734",
    LaunchDate:"May 2017",
    PossessionDate:"Ready to Move",
    Projecttype:"Residential ",
    projectarea:"10.41 Acres",
    Sizes:"995 - 1875 Sq.ft",
    ProjectUnits:"1572 Flats",
   LaunchDate:"May, 2017",
   PossessionDate:"Dec, 2022",
   TotalTowers:"11 Towers",
   TotalFloors:"23 Floors",
  ProjectStatus:"Ready To Move",
  PropertyType:"Residential",
  Configurations:"2BHK, 3BHK, 4BHK",
    location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.2857262981247!2d77.43616551549425!3d28.561181594056546!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cef70fc3a9861%3A0x9ff8321e65d81a96!2sAce%20Divino!5e0!3m2!1sen!2sin!4v1674031451895!5m2!1sen!2sin",
    ph1:"Located in the Posh location",
    ph2:"75% of green area",
    ph3:"Excellent Connectivity",
    ph4:"Zen Garden Present in the mid of Project",
    ph5:"Nearby are several international schools and hospitals",
    ph6:"World class amenities available in the Project",
    Configurations: "",
    ConstructionType: "",
    TotalFlats:"",
    GreenArea:"",
    Parkinglevel:"",
    Liftpertower:"",
    Noofparking:"",
    TotalFloors:"",
    Ceilingheight:"",
    Clubhousesize:"",
    MainDoorHeight:"",
    InternalDoorHeight:"",
    why1:"3 apartments per floor and skywalk for inter tower walking",
    why2:"Zen gardens in the middle of the tower",
    why3:"3 lifts in cluster of 8 apartments",
    why4:"Croquet area for residents and 75% open area for landscaping and sports amenities",
    why5:"Ensuring Well ventilated towers",
    why6:"Commercial complex with best brands available",
    q1:"Why to choose Ace Divino",
    a1:"Posh location,Excellent Connectivity",
    q2:"What is Ace Divino Address?",
    a2:"address",
    q3:"What is 2 BHK Starting Price",
    a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
    q4:"How many flat units available in Ace Divino?",
    a4:"1748 flats are available in the project",
    q5:"Does Ace Divino has kids play area",
    a5:"Yes, there is kids playing area available",
    q6:"What is the RERA no. of Ace Divino?",
    a6:"Ace Divino RERA NO. UPRERAPRJ6734",
    q7:"What is the Possession date of Ace Divino Sector 1?",
    a7:"Expected Possession date is around August 2023",
    q8:"Is this Project is Bank Approved?",
    a8:"Yes, Ace Divino is Approved by SBI Bank and HDFC Bank and many more",
    q9:"From where I can download Ace Divino Brochure?",
    a9:"You can download the brochure from the website. Download brochure link",
    q10:"Does Ace Divino have Penthouse?",
    a10:"Yes, the Project has Penthouse.",
    text:"Ace has an enhanced arrangement of different extravagant private undertakings and now they exhibit one of the ongoing projects in Noida Extension. The project – Ace Divino has an outstanding site plan and format configuration, guarantees to give a quiet, dynamic, energetic and secured gated experience The area of this new residential project in Noida Extension gives a preferred standpoint of being effortlessly available to different essential goals, like educational and health centers, eateries, shopping centers and corporate hubs.Ace Divino Greater Noida West will bring all the lavish and present day enhancements to spoil you, like the clubhouse, swimming pool, exercise center, garden area, plentiful parking spot, round the clock water and power supply, and so on. It will be a destination which will give a total new universe of extravagance and will be one of the best ongoing projects in Greater Noida West.Ace Divino in Noida Extension, is situated in a developing region, where infrastructural development is at a quick pace and this development will win great returns on investment for ACE Divino’s speculators."
  },
  { id:'2', 
    propertyname:"Ambience tiverton ",
    address1:"Sector 50, Noida",
    address2:"F-33, F Block, Sector 50, Noida",
    RERANO:"UPRERAPRJ4249",
    PropertyID:"HZ29",
    LaunchDate:"October 2014",
    PossessionDate:"Ready to Move",
    projectarea:"3.5 Acres",
    Sizes:"2548 - 3284 Sq.ft.",
    ProjectUnits:"270 Flats",
    LaunchDate:"Oct, 2014",
    PossessionDate:"March, 2020",
    TotalTowers:"7 Towers",
    TotalFloors:"26 Floors",
    ProjectStatus:"Ready To Move",
    PropertyType:"Residential",
    Configurations:"3BHK, 4BHK",
    Projecttype:"Residential ",
    location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3503.7506412924913!2d77.36810131549448!3d28.577249693330682!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce5b84c2b5a73%3A0xaf840e835cff6c27!2sAmbience%20Tiverton!5e0!3m2!1sen!2sin!4v1674031553468!5m2!1sen!2sin" ,
    why1:"Corner plot with two frontages for entry and adjacent to 32 Acres Green Belt",
    why2:"'A' RATED project by Noida Authority with 3-tier international standard security",
    why3:"Only 2 luxury residences per floor for a unique lifestyle with 2 levels of parking",
    why4:"Sprawling 20000 sqft clubhouse with interactive social zones",
    why5:"Strategically located at Sector 50 with easy access to Noida Expressway and Entertainment zone of Sector 18, Noida",
    why6:"Commercial complex with best brands available",
    Configurations: "",
    ConstructionType: "",
    TotalFlats:"",
    GreenArea:"",
    Parkinglevel:"",
    Liftpertower:"",
    Noofparking:"",
    TotalFloors:"",
    Ceilingheight:"",
    Clubhousesize:"",
    MainDoorHeight:"",
    InternalDoorHeight:"",
    q1:"Why to choose Ambience tiverton",
    a1:"Posh location,Excellent Connectivity",
    q2:"What is Ambience tiverton Address?",
    a2:"F-33, F Block, Sector 50, Noida",
    q3:"What is 2 BHK Starting Price",
    a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
    q4:"How many flat units available in Ambience tiverton ?",
    a4:"1748 flats are available in the project",
    q5:"Does Ambience tiverton has kids play area ?",
    a5:"Yes, there is kids playing area available",
    q6:"What is the RERA no. of Ambience tiverton ?",
    a6:"UPRERAPRJ4249",
    q7:"What is the Possession date of Ambience tiverton ?",
    a7:"Expected Possession date is around August 2023",
    q8:"Is this Project is Bank Approved ?",
    a8:"Yes,Ambience tiverton is Approved by SBI Bank and HDFC Bank and many more",
    q9:"From where I can download Ambience tiverton Brochure ?",
    a9:"You can download the brochure from the website. Download brochure link",
    q10:"Does Ambience tiverton have Penthouse ?",
    a10:"Yes, the Project has Penthouse."
    
  },
  { id:'3', 
    propertyname:"Godrej Woods",
    address1:"Sector 43, Noida",
    address2:"Block A, Sector 43, Noida, Uttar Pradesh 201303",
    RERANO:"UPRERAPRJ704730",
    PropertyID:"HZ29",
    status:"Ready to Move",
    LaunchDate:"May 2017",
    PossessionDate:"Ready to Move",
    Projecttype:"Residential",
    projectarea:"11 Acres",
    Sizes:"1255 - 3759 Sq.ft.",
    ProjectUnits:"1100 Flats",
   LaunchDate:"Jan, 2021",
   why1:"Godrej Woods is gold rated by IGBC (Indian Green building council)",
    why2:"Urban Forest Themed Project",
    why3:"90 meters long elevated walkway that runs over the forest",
    why4:"Singapore-style living in Central Noida",
    why5:"2 Infinity edge pools overlooking the forest and a Pool with Jacuzzi",
    why6:"Project just next to 97-acres Golf Course",
   PossessionDate:"July, 2025",
   TotalTowers:"10 Towers",
   TotalFloors:"34 Floors",
  ProjectStatus:"Under Construction",
  PropertyType:"Residential",
  Configurations:"2BHK, 3BHK, 5BHK",
    location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.3666738551206!2d77.34894121549411!3d28.558750094166488!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce5d5046eee85%3A0x9ed7749be19b1b56!2sGodrej%20Woods%2C%20Sector%2043%2C%20Noida!5e0!3m2!1sen!2sin!4v1674031636046!5m2!1sen!2sin",   
    Configurations: "",
    ConstructionType: "",
    TotalFlats:"",
    GreenArea:"",
    Parkinglevel:"",
    Liftpertower:"",
    Noofparking:"",
    TotalFloors:"",
    Ceilingheight:"",
    Clubhousesize:"",
    MainDoorHeight:"",
    InternalDoorHeight:"",
    q1:"Why to choose Godrej Woods ?",
    a1:"Posh location,Excellent Connectivity",
    q2:"What is Godrej Woods Address ?",
    a2:"Block A, Sector 43, Noida, Uttar Pradesh 201303",
    q3:"What is 2 BHK Starting Price ?",
    a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
    q4:"How many flat units available in Godrej Woods ? ",
    a4:"1748 flats are available in the project",
    q5:"Does Godrej Woods has kids play area ?",
    a5:"UPRERAPRJ704730",
    q6:"What is the RERA no. of Godrej Woods ?",
    a6:"UPRERAPRJ704730",
    q7:"What is the Possession date of  Godrej Woods ?",
    a7:"Expected Possession date is around August 2023",
    q8:"Is this Project is Bank Approved ?",
    a8:"Yes,Godrej Woods is Approved by SBI Bank and HDFC Bank and many more",
    q9:"From where I can download Godrej Woods Brochure ?",
    a9:"You can download the brochure from the website. Download brochure link",
    q10:"Does Godrej Woods have Penthouse ?",
    a10:"Yes, the Project has Penthouse."
    
  },
  { id:'4', 
    propertyname:"Trident Reso",
    address1:"Greater Noida West",
    address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
    RERANO:"UPRERAPRJ785019",
    PropertyID:"HZ29",
    status:"Ready to Move",
    LaunchDate:"May 2017",
    PossessionDate:"Ready to Move",
    Projecttype:"Residential",
    projectarea:"3.21 Acres",
    Sizes:"1272 - 1892 Sq.ft.",
    ProjectUnits:"576 Flats",
   LaunchDate:"Feb, 2021",
   PossessionDate:"Dec, 2025",
   TotalTowers:"5 Towers",
   TotalFloors:"23 Floors",
    ProjectStatus:"Under Construction",
    PropertyType:"Residential",
    Configurations:"2.5BHK, 3BHK , 3.5BHK, 4BHK",
    location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
    ph1:"Prime Location Sector- 1, Greater Noida (West)",
    ph2:"70% of green area ",
    ph3:"Two Side Open Plot and Three Side Park View",
    ph4:"Earthquake Resistant R.C.C Framed Structure",
    ph5:"Three-Tier Security system is available",
    ph6:"Clubhouse with exclusive recreational amenities",
    Configurations: "",
    ConstructionType: "",
    TotalFlats:"",
    GreenArea:"",
    Parkinglevel:"",
    Liftpertower:"",
    Noofparking:"",
    TotalFloors:"",
    Ceilingheight:"",
    Clubhousesize:"",
    MainDoorHeight:"",
    InternalDoorHeight:"",
    why1:"Godrej Woods is gold rated by IGBC (Indian Green building council)",
    why2:"Urban Forest Themed Project",
    why3:"90 meters long elevated walkway that runs over the forest",
    why4:"Singapore-style living in Central Noida",
    why5:"2 Infinity edge pools overlooking the forest and a Pool with Jacuzzi",
    why6:"Project just next to 97-acres Golf Course",
    q1:"Why to chooseTrident Reso ?",
    a1:"Posh location,Excellent Connectivity",
    q2:"What is Trident Reso Address ?",
    a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
    q3:"What is 2 BHK Starting Price ?",
    a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
    q4:"How many flat units available in Trident Reso ? ",
    a4:"1748 flats are available in the project",
    q5:"Does Trident Reso has kids play area ?",
    a5:"UPRERAPRJ704730",
    q6:"What is the RERA no. of Trident Reso ?",
    a6:"UPRERAPRJ785019",
    q7:"What is the Possession date of  Trident Reso ?",
    a7:"Expected Possession date is around August 2023",
    q8:"Is this Project is Bank Approved ?",
    a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
    q9:"From where I can download Trident Reso Brochure ?",
    a9:"You can download the brochure from the website. Download brochure link",
    q10:"Does Trident Reso have Penthouse ?",
    a10:"Yes, the Project has Penthouse."
    
  },{ id:'5', 
  propertyname:"Ace Startlit",
  address1:"Sector 152, Noida",
  address2:"SC-01/09, Sector 152, Noida, Uttar Pradesh 201303",
  RERANO:"UPRERAPRJ677294",
  PropertyID:"HZ29",
  status:"Ready to Move",
  LaunchDate:"May 2017",
  PossessionDate:"Ready to Move",
  Projecttype:"Residential",
  projectarea:"7 Acres",
  Sizes:"1350 - 1775 Sq.ft.",
  ProjectUnits:"496 Flats",
 LaunchDate:"May 2021",
 PossessionDate:"April 2025",
 TotalTowers:"5 Towers",
 TotalFloors:"G+16 Floors",
ProjectStatus:"Under Construction",
PropertyType:"Residential",
Configurations:"2BHK, 3BHK",
why1:"Low density development with only 5 towers on 7 acres of plot area",
    why2:"3 side open views of the city skyline",
    why3:"Unique glass facade residencies with glass railings and ultra modern double height entrance lobby",
    why4:"Corner plot with access from 45m wide road on two sides",
    why5:"Privacy with no unit facing each other",
    why6:"Dedicated recreational zone for each tower",
  location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
  Configurations: "",
  ConstructionType: "",
  TotalFlats:"",
  GreenArea:"",
  Parkinglevel:"",
  Liftpertower:"",
  Noofparking:"",
  TotalFloors:"",
  Ceilingheight:"",
  Clubhousesize:"",
  MainDoorHeight:"",
  InternalDoorHeight:"",
  q1:"Why to chooseTrident Reso ?",
  a1:"Posh location,Excellent Connectivity",
  q2:"What is Trident Reso Address ?",
  a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
  q3:"What is 2 BHK Starting Price ?",
  a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
  q4:"How many flat units available in Trident Reso ? ",
  a4:"1748 flats are available in the project",
  q5:"Does Trident Reso has kids play area ?",
  a5:"UPRERAPRJ704730",
  q6:"What is the RERA no. of Trident Reso ?",
  a6:"UPRERAPRJ785019",
  q7:"What is the Possession date of  Trident Reso ?",
  a7:"Expected Possession date is around August 2023",
  q8:"Is this Project is Bank Approved ?",
  a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
  q9:"From where I can download Trident Reso Brochure ?",
  a9:"You can download the brochure from the website. Download brochure link",
  q10:"Does Trident Reso have Penthouse ?",
  a10:"Yes, the Project has Penthouse."
  
},{ id:'6', 
propertyname:"Kalpataru Vista ",
address1:"Sector 128 Noida",
address2:"Kalpataru Vista, Plot B 24 C Wish Town, Sector 128 Noida, Uttar Pradesh 201304",
RERANO:" UPRERAPRJ14980",
PropertyID:"HZ29",
status:"Ready to Move",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"3 Acres",
Sizes:"3011 - 4145 Sq.ft.",
ProjectUnits:"250 Flats",
LaunchDate:"May, 2018",
PossessionDate:"April 2024",
TotalTowers:"April 2024",
TotalFloors:"34 Floors",
ProjectStatus:"Under Construction",
PropertyType:"Residential",
Configurations:"3BHK, 4BHK",
why1:"30 acres of a 9 hole executive golf course designed by Graham Cooke",
    why2:"Pre Certified Gold Rated Green Building",
    why3:"9 splendid water bodies and 62 bunkers in the vicinity",
    why4:"Spectacular infinity pool overlooking the golf course and the vast horizon",
    why5:"Shaded Cabanas with Lush Landscaped Greens",
    why6:"Four elevators along with a service elevator for the resident's privacy and security",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
why1:"Ultra-luxurious apartments and sky villa penthouse with a 360 degree green view",
    why2:"Strategically located near Noida Expressway with 15 hole golf course in close vicinity",
    why3:"Low-density project with 3 flats per floor",
    why4:"Club laureate offers world's finest list of luxuries along with bowling alley",
    why5:"Properties with 100% power backup available",
    why6:"Club laureate offers worlds finest list of luxuries along with bowling alley",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'7', 
propertyname:"Parx Laureate",
address1:"Sector 108, Noida",
address2:"H-01 Sector 108, Noida Expressway, Noida, 201304.",
RERANO:" UPRERAPRJ5998",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"11 Acres",
Sizes:"3302- 4874 Sq.ft.",
ProjectUnits:"570 Flats",
LaunchDate:"May, 2013",
PossessionDate:"Ready To Move",
TotalTowers:"9 Towers",
TotalFloors:"21 Floors",
ProjectStatus:"Ready To Move",
PropertyType:"Residential",
Configurations:"3BHK, 4BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
why1:"Ultra-luxurious apartments and sky villa penthouse with a 360 degree green view",
    why2:"Strategically located near Noida Expressway with 15 hole golf course in close vicinity",
    why3:"Low-density project with 3 flats per floor",
    why4:"Club laureate offers world's finest list of luxuries along with bowling alley",
    why5:"Well connected through Noida Expressway",
    why6:"Metro connectivity",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'8', 
propertyname:"Tata Eureka",
address1:"Sector 150 Noida",
address2:"SC-01 A1, Sector 150, Noida, Uttar Pradesh 201310",
RERANO:"UPRERAPRJ5448",
PropertyID:"HZ29",
status:"Under Construction",
LaunchDate:"May 2017",
Projecttype:"Residential",
projectarea:"20 Acres",
Sizes:"1100 - 1575 Sq.ft.",
ProjectUnits:"1160 Flats",
LaunchDate:"Sep, 2019",
PossessionDate:"Sep, 2023",
TotalTowers:"20 Towers",
TotalFloors:"28 Floors",
ProjectStatus:"Under Construction",
PropertyType:"Residential",
Configurations:"2BHK, 3BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
why1:"Pre-certified as Gold Rated by Indian Green Building Council and also coded green by UP-RERA",
    why2:"Smart Home Automation Features Like Gas Leakage Detectors, the Motion Sensors and Digital Door Locks",
    why3:"Separate sports block with International-sized tennis court",
    why4:"Open space for cultural activities with 8 acres of green area and Wi-Fi enabled gazebos",
    why5:"4 sides open layouts with maximum utilization of space",
    why6:"9-Hole Golf Course in close proximity",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'9', 
propertyname:"County 107",
address1:"Sector 107, Noida",
address2:"GH 01A, B (ALPHA, Sector 107, Noida, Uttar Pradesh 201301",
RERANO:"UPRERAPRJ837374",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"5 Acres",
Sizes:"2084 - 3904 Sq.ft.",
ProjectUnits:"245 Flats",
LaunchDate:"May, 2019",
PossessionDate:"Dec, 2023",
TotalTowers:"4 Towers",
TotalFloors:"31 Floors",
ProjectStatus:"Under Construction",
PropertyType:"Residential",
Configurations:"4BHK, 5BHK",
why1:"1st Housing Project in India with Elevated Walkway",
why2:"Well-connected to Noida-Greater Noida Expressway",
why3:"State-of-the-art architecture with Vertical Garden",
why4:"Home automation system including; door camera and intercom, climate, ventilation and lighting modes",
why5:"Introducing Noida’s most exclusive residence - County 107 with high standard features and amenities",
why6:"Indoor Temperature Controlled Swimming Pool",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",

Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'10', 
propertyname:"Eldeco Live By The Greens",
address1:"Sector 150, Noida",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ743918",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"20 Acres",
Sizes:"1137 - 1404 Sq.ft.",
ProjectUnits:"1500 Flats",
LaunchDate:"Feb, 2018",
PossessionDate:"Dec 2023",
TotalTowers:"17 Towers",
TotalFloors:"G + 22 Floors",
ProjectStatus:"Under Construction",
PropertyType:"Residential",
Configurations:"2BHK, 3BHK",
why1:"Greenest sector of Noida with 80 percent of green cover",
    why2:"Cric Kingdom cricket academy by Rohit Sharma",
    why3:"Project spread around a cricket field to relax and rejuvenate life",
    why4:"35,000 sq. ft. club house with resort like lifestyle and poolside cabanas",
    why5:"Easily accessible location through 6-lane Noida-Greater Noida Expressway",
    why6:"Shaheed Bhagat Singh Park, spread over 40 acres, the biggest in the country is at a walking distance",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'11', 
propertyname:"Trident Reso",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ785019",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"",
Sizes:"",
ProjectUnits:"",
LaunchDate:"",
PossessionDate:"",
TotalTowers:"",
TotalFloors:"",
ProjectStatus:"",
PropertyType:"",
Configurations:"",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'12', 
propertyname:"Trident Reso",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ785019",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"",
Sizes:"",
ProjectUnits:"",
LaunchDate:"",
PossessionDate:"",
TotalTowers:"",
TotalFloors:"",
ProjectStatus:"",
PropertyType:"",
Configurations:"",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'13', 
propertyname:"Trident Reso",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ785019",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"",
Sizes:"",
ProjectUnits:"",
LaunchDate:"",
PossessionDate:"",
TotalTowers:"",
TotalFloors:"",
ProjectStatus:"",
PropertyType:"",
Configurations:"",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'14', 
propertyname:"Trident Reso",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ785019",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"",
Sizes:"",
ProjectUnits:"",
LaunchDate:"",
PossessionDate:"",
TotalTowers:"",
TotalFloors:"",
ProjectStatus:"",
PropertyType:"",
Configurations:"",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'15', 
propertyname:"Trident Reso",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ785019",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"",
Sizes:"",
ProjectUnits:"",
LaunchDate:"",
PossessionDate:"",
TotalTowers:"",
TotalFloors:"",
ProjectStatus:"",
PropertyType:"",
Configurations:"",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'16', 
propertyname:"Trident Reso",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ785019",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"",
Sizes:"",
ProjectUnits:"",
LaunchDate:"",
PossessionDate:"",
TotalTowers:"",
TotalFloors:"",
ProjectStatus:"",
PropertyType:"",
Configurations:"",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'17', 
propertyname:"Trident Reso",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ785019",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"",
Sizes:"",
ProjectUnits:"",
LaunchDate:"",
PossessionDate:"",
TotalTowers:"",
TotalFloors:"",
ProjectStatus:"",
PropertyType:"",
Configurations:"",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

},{ id:'18', 
propertyname:"Trident Reso",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ785019",
PropertyID:"HZ29",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"",
Sizes:"",
ProjectUnits:"",
LaunchDate:"",
PossessionDate:"",
TotalTowers:"",
TotalFloors:"",
ProjectStatus:"",
PropertyType:"",
Configurations:"",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
ph1:"Prime Location Sector- 1, Greater Noida (West)",
ph2:"70% of green area ",
ph3:"Two Side Open Plot and Three Side Park View",
ph4:"Earthquake Resistant R.C.C Framed Structure",
ph5:"Three-Tier Security system is available",
ph6:"Clubhouse with exclusive recreational amenities",
Configurations: "",
ConstructionType: "",
TotalFlats:"",
GreenArea:"",
Parkinglevel:"",
Liftpertower:"",
Noofparking:"",
TotalFloors:"",
Ceilingheight:"",
Clubhousesize:"",
MainDoorHeight:"",
InternalDoorHeight:"",
q1:"Why to chooseTrident Reso ?",
a1:"Posh location,Excellent Connectivity",
q2:"What is Trident Reso Address ?",
a2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
q3:"What is 2 BHK Starting Price ?",
a3:"2 BHK flat of Size 995 Sq. ft. Starts from Rs. 75 lakh onwards",
q4:"How many flat units available in Trident Reso ? ",
a4:"1748 flats are available in the project",
q5:"Does Trident Reso has kids play area ?",
a5:"UPRERAPRJ704730",
q6:"What is the RERA no. of Trident Reso ?",
a6:"UPRERAPRJ785019",
q7:"What is the Possession date of  Trident Reso ?",
a7:"Expected Possession date is around August 2023",
q8:"Is this Project is Bank Approved ?",
a8:"Yes,Trident Reso is Approved by SBI Bank and HDFC Bank and many more",
q9:"From where I can download Trident Reso Brochure ?",
a9:"You can download the brochure from the website. Download brochure link",
q10:"Does Trident Reso have Penthouse ?",
a10:"Yes, the Project has Penthouse."

}
  ];

